---
- name: Enable ip_nonlocal_bind
  sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: '1'
    state: present

- name: Install HAProxy
  apt: name=haproxy state=present

- name: Generate HAProxy configuration
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
  notify: restart HAProxy

- name: Install hatop
  apt: name=hatop state=present

- name: Install keepalived
  apt: name=keepalived state=present

- name: Generate keepalived configuration
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: 0644
  notify: restart keepalived
