resources:
- dind-docker.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- patch: |
    kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: act-runner-vol
    spec:
      storageClassName:
- patch: |
    apiVersion: v1
    kind: Secret
    metadata:
      name: runner-secret
    $patch: delete
