---
- name: Add rook ceph repo
  kubernetes.core.helm_repository:
    name: rook-release
    repo_url: https://charts.rook.io/release

- name: Copy ceph operator template
  template:
    src: "ceph-operator-values.yaml.j2"
    dest: "{{ kube_config_dir }}/ceph-operator-values.yaml"
    mode: 0644

- name: Deploy ceph operator
  kubernetes.core.helm:
    name: rook-ceph
    chart_ref: rook-release/rook-ceph
    namespace: rook-ceph
    create_namespace: yes
    values_files:
      - "{{ kube_config_dir }}/ceph-operator-values.yaml"

- name: Copy ceph cluster template
  template:
    src: "ceph-cluster-values.yaml.j2"
    dest: "{{ kube_config_dir }}/ceph-cluster-values.yaml"
    mode: 0644

- name: Deploy ceph cluster
  kubernetes.core.helm:
    name: rook-ceph-cluster
    chart_ref: rook-release/rook-ceph-cluster
    namespace: rook-ceph
    values_files:
      - "{{ kube_config_dir }}/ceph-cluster-values.yaml"
