all:
  hosts:
    node1:
      ansible_user: ubuntu
      ansible_sudo_pass: <placeholder>
      ansible_host: 192.168.1.191
      ip: 192.168.1.191
      access_ip: 192.168.1.191
    node2:
      ansible_user: ubuntu
      ansible_sudo_pass: <placeholder>
      ansible_host: 192.168.1.192
      ip: 192.168.1.192
      access_ip: 192.168.1.192
    node3:
      ansible_user: ubuntu
      ansible_sudo_pass: <placeholder>
      ansible_host: 192.168.1.193
      ip: 192.168.1.193
      access_ip: 192.168.1.193
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
        node3:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
